version: "3.9"
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG_MODE}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL_DOCKER}
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A notification_service_project worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
  celery-beat:
    build: .
    command: celery -A notification_service_project beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}

volumes:
  postgres_data:
