# Generated by Django 4.1.3 on 2022-11-27 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveBigIntegerField(help_text=' Номер телефона клиента в формате 7XXXXXXXXXX. Уникален для каждого клиента.', unique=True, validators=[django.core.validators.MinValueValidator(70000000000), django.core.validators.MaxValueValidator(79999999999), django.core.validators.RegexValidator(code='invalid_phone_number', message='The mobile number must have the format: 7XXXXXXXXXX', regex='^7\\d{10}$')], verbose_name=' Номер телефона')),
                ('operator_code', models.CharField(help_text='Код оператора в формате XXX. Задаётся автоматически из номера телефона.', max_length=3, validators=[django.core.validators.RegexValidator(code='invalid_mobile_code', regex='^\\d{3}$')], verbose_name='Код оператора')),
                ('tag', models.CharField(max_length=255, verbose_name='Тег (произвольная метка)')),
                ('timezone', models.CharField(help_text='Часовой пояс клиента в формате "Europe/Moscow".', max_length=255, verbose_name='Часовой пояс')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start', models.DateTimeField(verbose_name='Дата и время начала рассылки')),
                ('date_time_stop', models.DateTimeField(verbose_name='Дата и время окончания рассылки')),
                ('time_interval_start', models.TimeField(blank=True, null=True, verbose_name='Начало временного интервала')),
                ('time_interval_stop', models.TimeField(blank=True, null=True, verbose_name='Конец временного интервала')),
                ('text', models.TextField(verbose_name='Текст рассылки')),
                ('tags', models.TextField(help_text='Список тэгов для рассылки. Тэги должны быть отделены запятыми.', verbose_name='Список тэгов')),
                ('status', models.CharField(choices=[('N', 'Not Started'), ('S', 'Started'), ('F', 'Finished')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Статус отправки сообщения')),
                ('date_time_send', models.DateTimeField(auto_now=True, verbose_name='Дата и время отправки сообщения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.client')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
            ],
        ),
    ]
